### ISSUE TITLE
asset tag helpers aren't linking to production assets

### ISSUE THREAD

**Issue by icco** [Ortuna/padrino-pipeline#15]
Even though I've precompiled my assets, and am running with `RACK_ENV=PRODUCTION`, The helpers generate `<link href="/css/application.css?1387948987" media="screen" rel="stylesheet" type="text/css">` instead of `<link href="/css/application-c2151ed2bcc1d4e607134f180c611b2f.css" media="screen" rel="stylesheet" type="text/css"`.

Thoughts?

Code: https://github.com/icco/creeper

**Comment by Ortuna** [comment]
Could you give this another go with master?  `PADRINO_ENV` => `RACK_ENV` change was not implemented except just a few minutes ago.  You may also set `config.enable_compression = true` when configuring the pipeline.

**Comment by Ortuna** [comment]
@icco closing for now.  Please reopen if you still see this error :cat:
